### ISSUE TITLE
Error: unrecognized arguments: --is_gaussian False

### ISSUE THREAD

**Issue by christianll9** [Demon0312/Heterogeneous-Attentions-PDP-DRL#1]
The following command from the Quick Start is not working:
```
python generate_data.py --name validation --seed 1234 --is_gaussian False --sigma 1.0
```

I receive following error:
```
generate_data.py: error: unrecognized arguments: --is_gaussian False
```

If I use `is_guassian` instead of `is_gaussian`, it works.

**Comment by jingwenli0312** [comment]
Hi,
I have modified the file "genearate_data.py", and the "gua" has been changed to "gau".
Sorry for the inconvenience.

Best regards,
Jingwen

________________________________
From: Christian ***@***.***>
Sent: Friday, March 26, 2021 2:44 AM
To: Demon0312/Heterogeneous-Attentions-PDP-DRL ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Demon0312/Heterogeneous-Attentions-PDP-DRL] Error: unrecognized arguments: --is_gaussian False (#1)

        - External Email -



The following command from the Quick Start is not working:

python generate_data.py --name validation --seed 1234 --is_gaussian False --sigma 1.0


I receive following error:

generate_data.py: error: unrecognized arguments: --is_gaussian False


If I use is_guassian instead of is_gaussian, it works.
